image: node:latest

cache:
 paths:
  - "$CI_PROJECT_DIR/frontend/.npm/"
  - "$CI_PROJECT_DIR/frontend/node_modules"

before_script:
  - cd ./frontend
  - npm install

build_frontend:
 stage: build
 script:
  - npm run lint
  - npm run build

test_frontend:
 stage: test
 script:
  - set -xe
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
  - apt-get update -yqqq
  - apt-get install -y google-chrome-stable
  - npm run test-ci
